# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vabrageo <vabrageo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/08 15:31:22 by vabrageo          #+#    #+#              #
#    Updated: 2019/10/21 16:25:35 by vabrageo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = gcc
CFLAGS =  -Wall -Wextra -Werror -I includes

SRCS =	ft_bzero.c \
		ft_memcpy.c \
		ft_memccpy.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_memcpy.c \
		ft_memmove.c \
		ft_memset.c \
		ft_strlcpy.c \
		ft_strlcat.c \
		ft_strchr.c \
		ft_strrchr.c \
		ft_strnstr.c \
		ft_strncmp.c \
		ft_atoi.c \
		ft_isalpha.c \
		ft_isdigit.c \
		ft_isalnum.c \
		ft_isascii.c \
		ft_isprint.c \
		ft_toupper.c \
		ft_tolower.c \
		ft_strdup.c \
		ft_substr.c \
		ft_strjoin.c \
		ft_strtrim.c \
		ft_calloc.c \
		ft_split.c \
		ft_itoa.c \
		ft_putchar_fd.c \
		ft_putstr_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_strmapi.c \
		ft_strlen.c
		
SRCSB =	ft_lstadd_back.c \
		ft_lstadd_front.c \
		ft_ischar.c \
		ft_lstclear.c \
		ft_lstdelone.c \
		ft_lstiter.c \
		ft_lstmap.c \
		ft_lstnew.c \
		ft_lstlast.c \
		ft_lstsize.c

OBJS  = ${SRCS:.c=.o}
OBJSB = ${SRCSB:.c=.o}
AR  = ar rc
ARB = ar rcs
all: $(NAME)

$(NAME): ${OBJS}
	${AR} ${NAME} ${OBJS} $?
bonus: $(NAME) ${OBJSB}
	${ARB} ${NAME} ${OBJSB} $?
clean:
	rm -rf *.o
fclean: clean
	rm -rf $(NAME)
re: fclean all bonus

.PHONY: all clean fclean re